In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor()

In [5]:
train= pd.read_csv('train.csv')
train

,ID,YEAR,T2M_RANGE,T2M_MAX,T2M_MIN,RH2M,PS,WS10M,QV2M,T2M,VACATION_RATE
0,0,1982.0,-241.552430,29.798545,13.691128,71.652934,89.725069,3.658959,8.474319,21.723403,64.184741
1,1,1982.0,-241.819997,30.902708,15.298046,69.754933,89.865668,3.529113,8.988374,22.911522,42.649137
2,2,1982.0,-241.883202,30.296561,14.660419,66.661416,89.846273,4.217007,8.474923,22.994887,52.819141
3,3,1982.0,-242.007629,30.803224,15.246491,67.621173,90.029795,4.484080,9.005508,23.594655,39.445489
4,4,1982.0,-240.659332,32.500906,15.303059,62.097329,89.825707,3.057211,8.307515,24.536776,46.444289
...,...,...,...,...,...,...,...,...,...,...,...
1434,1434,2009.0,-246.654914,30.644813,20.268662,78.611410,89.333566,6.433604,13.258977,26.685352,6.391643
1435,1435,2009.0,-247.651283,29.857874,20.425241,78.136636,89.324790,7.638996,12.717079,25.991700,1.920453
1436,1436,2009.0,-247.594571,30.330303,21.123513,77.497787,89.334675,8.939772,13.058350,26.619025,7.144639
1437,1437,2009.0,-247.083708,30.646652,20.883603,75.857655,89.465743,7.663743,12.805387,26.923294,4.886901
1438,1438,2009.0,-246.099233,32.191877,21.121979,75.757341,89.528083,6.426315,13.028215,27.318661,11.217462

In [6]:
test=pd.read_csv('test.csv')
test

,ID,YEAR,T2M_RANGE,T2M_MAX,T2M_MIN,RH2M,PS,WS10M
0,1440,2009.0,-309.569706,32.919144,17.735611,74.415249,82.443918,6.513046
1,1441,2009.0,-310.763533,32.340370,17.955298,75.232482,82.320169,5.163099
2,1442,2009.0,-313.096292,29.670217,17.788919,80.950265,82.456590,3.974139
3,1443,2009.0,-312.110915,29.586632,16.777071,82.254238,82.460926,5.504794
4,1444,2009.0,-312.445008,30.088295,17.233512,81.311915,82.326908,5.634695
...,...,...,...,...,...,...,...,...
695,2135,2022.0,-310.857597,28.357413,15.023100,86.599317,82.511107,2.637025
696,2136,2022.0,-312.033878,26.943856,14.236847,85.965911,82.748450,3.636588
697,2137,2022.0,-312.869384,26.542410,14.972372,88.082615,82.626626,3.840101
698,2138,2022.0,-308.938303,27.599339,12.882619,84.585012,82.632252,3.306362
699,2139,2022.0,-310.589598,28.341680,14.604535,85.173914,82.874200,3.522586

In [7]:
X1_train=train.drop(['T2M','QV2M','VACATION_RATE'],axis=1)
X1_train

,ID,YEAR,T2M_RANGE,T2M_MAX,T2M_MIN,RH2M,PS,WS10M
0,0,1982.0,-241.552430,29.798545,13.691128,71.652934,89.725069,3.658959
1,1,1982.0,-241.819997,30.902708,15.298046,69.754933,89.865668,3.529113
2,2,1982.0,-241.883202,30.296561,14.660419,66.661416,89.846273,4.217007
3,3,1982.0,-242.007629,30.803224,15.246491,67.621173,90.029795,4.484080
4,4,1982.0,-240.659332,32.500906,15.303059,62.097329,89.825707,3.057211
...,...,...,...,...,...,...,...,...
1434,1434,2009.0,-246.654914,30.644813,20.268662,78.611410,89.333566,6.433604
1435,1435,2009.0,-247.651283,29.857874,20.425241,78.136636,89.324790,7.638996
1436,1436,2009.0,-247.594571,30.330303,21.123513,77.497787,89.334675,8.939772
1437,1437,2009.0,-247.083708,30.646652,20.883603,75.857655,89.465743,7.663743
1438,1438,2009.0,-246.099233,32.191877,21.121979,75.757341,89.528083,6.426315

In [8]:
y1_train=train["QV2M"]
y1_train

0        8.474319
1        8.988374
2        8.474923
3        9.005508
4        8.307515
          ...
1434    13.258977
1435    12.717079
1436    13.058350
1437    12.805387
1438    13.028215
Name: QV2M, Length: 1439, dtype: float64

In [9]:
#to predict QV2M using train
regressor.fit(X1_train,y1_train)
pred1=regressor.predict(X1_train) 
pred1.round(1)

array([ 8.5,  8.9,  8.5, ..., 13.1, 12.8, 13.1])

In [10]:
y1_train.round(1)

0        8.5
1        9.0
2        8.5
3        9.0
4        8.3
        ...
1434    13.3
1435    12.7
1436    13.1
1437    12.8
1438    13.0
Name: QV2M, Length: 1439, dtype: float64

In [11]:
accuracy=regressor.score(X1_train,y1_train)
accuracy

0.9971064101748832

In [12]:
test

,ID,YEAR,T2M_RANGE,T2M_MAX,T2M_MIN,RH2M,PS,WS10M
0,1440,2009.0,-309.569706,32.919144,17.735611,74.415249,82.443918,6.513046
1,1441,2009.0,-310.763533,32.340370,17.955298,75.232482,82.320169,5.163099
2,1442,2009.0,-313.096292,29.670217,17.788919,80.950265,82.456590,3.974139
3,1443,2009.0,-312.110915,29.586632,16.777071,82.254238,82.460926,5.504794
4,1444,2009.0,-312.445008,30.088295,17.233512,81.311915,82.326908,5.634695
...,...,...,...,...,...,...,...,...
695,2135,2022.0,-310.857597,28.357413,15.023100,86.599317,82.511107,2.637025
696,2136,2022.0,-312.033878,26.943856,14.236847,85.965911,82.748450,3.636588
697,2137,2022.0,-312.869384,26.542410,14.972372,88.082615,82.626626,3.840101
698,2138,2022.0,-308.938303,27.599339,12.882619,84.585012,82.632252,3.306362
699,2139,2022.0,-310.589598,28.341680,14.604535,85.173914,82.874200,3.522586

In [13]:
y1_test=regressor.predict(test)
y1_test #T2M prediction on test.csv

array([11.67548665, 11.73491821, 12.08905128, 11.63750274, 11.7724141 ,
       11.59725762, 12.80573608, 12.4115934 , 12.02830134, 11.63725729,
       11.59126123, 11.33553121, 11.35858648, 11.42779876, 11.83118896,
       11.89023898, 11.53783708, 11.36730908, 11.30059267, 11.36082405,
       11.33332687, 11.36449553, 11.30271204, 11.48126062, 11.29523672,
       11.27079024, 11.30067109, 11.30067109, 11.38693179, 11.48305287,
       11.39385479, 11.66993395, 11.68244419, 11.44755421, 12.77568717,
       12.47863723, 12.91415171, 12.78393247, 12.8952298 , 12.73027602,
       13.11881297, 12.84444696, 12.55583237, 12.49285054, 12.00825405,
       12.11325908, 11.80769217, 11.69717593, 11.60887602, 11.93238571,
       11.65814072, 11.89916656, 11.85749776, 11.82137229, 12.22311936,
       12.19023818, 11.59776354, 11.70298795, 11.60547889, 11.93579531,
       12.00594042, 12.41366156, 12.42705408, 11.97190188, 11.99154654,
       11.98757927, 11.92081032, 11.87274937, 11.5627117 , 11.56210061,
       11.50768032, 11.42816886, 11.35122429, 11.34535201, 11.35821411,
       11.30271204, 11.31531614, 11.24944323, 11.24769313, 11.30067109,
       11.31069625, 11.55751853, 11.24769313, 11.26722363, 11.26250499,
       11.49522355, 12.02170484, 12.45101237, 12.45664828, 12.60125157,
       11.92737338, 12.64771688, 12.03014178, 12.83135495, 12.74924395,
       12.05508425, 11.78811124, 11.66126117, 11.65739396, 11.71696691,
       11.4164458 , 11.4189959 , 11.68828512, 11.72404067, 11.49714128,
       11.59616582, 11.87282736, 11.60307288, 11.60260029, 11.59772106,
       11.56198601, 11.56133764, 11.49331928, 11.49586381, 12.19134338,
       11.52425624, 11.55625496, 11.57100131, 11.29727766, 11.26784785,
       11.2463298 , 11.57128019, 11.29523672, 11.24412653, 11.24769313,
       11.24769313, 11.29613305, 11.29914543, 11.31531614, 11.30067109,
       11.2452798 , 11.29914543, 11.41380414, 11.24225876, 11.28507304,
       11.4536023 , 11.66613208, 11.80504726, 11.40274903, 11.81811468,
       12.67872996, 12.75432564, 12.83058553, 12.67680002, 12.54617526,
       12.64888722, 12.76068704, 12.56431203, 11.91401216, 11.71137969,
       11.65739396, 11.76368184, 11.65025619, 11.76770135, 11.66356333,
       11.69114814, 11.65503778, 11.46673812, 11.47743131, 11.72651053,
       12.00936566, 11.82788594, 11.45514605, 11.52299833, 11.54347614,
       11.50564015, 11.45949631, 11.62069648, 11.47723978, 11.50795283,
       11.58904956, 11.30340883, 11.31473942, 11.31789628, 11.28812415,
       11.31456051, 11.2463298 , 11.23984543, 11.35410855, 11.31993722,
       11.2512574 , 11.27079024, 11.24412653, 11.29710449, 11.36290821,
       11.41021293, 11.24769313, 11.33437687, 11.52934664, 11.4805244 ,
       11.74724117, 12.9187234 , 12.78504091, 12.71754213, 12.9498184 ,
       12.93055361, 13.14914552, 12.62704272, 12.72473493, 12.26694225,
       12.13034414, 11.59102892, 11.81856931, 11.81860035, 11.58525055,
       11.61703649, 12.17189469, 11.6140679 , 11.55028451, 11.74639373,
       12.16668083, 11.67069134, 11.61134752, 12.22783536, 11.96963905,
       12.20250429, 11.54168564, 11.70558578, 11.98204512, 11.8742586 ,
       11.98702715, 11.85032893, 11.45156433, 11.34805774, 11.39207074,
       11.45190426, 11.27643404, 11.24944323, 11.31999489, 11.2512574 ,
       11.24769313, 11.2512574 , 11.26722363, 11.24587663, 11.2452798 ,
       11.30067109, 11.31531614, 11.48029624, 11.30816425, 11.67591471,
       11.29550608, 11.26250499, 11.37995766, 11.69184832, 12.10085323,
       12.76309361, 12.41640187, 13.08087551, 12.56815966, 12.64805249,
       12.65077408, 12.95896948, 12.89977283, 11.87305223, 11.8528364 ,
       12.12260189, 11.92609323, 11.52010833, 11.70621274, 11.70229403,
       11.81083702, 11.81306726, 11.62572146, 11.96171929, 11.89418384,
       11.51972848, 11.4351362 , 11.53579908, 12.37456218, 11.68370344,
       12.16851003, 11.60829034, 11.47617865, 11.50954905, 11.30914668,
       11.442415  , 11.24493977, 11.30340883, 11.30271204, 11.36375605,
       11.33749031, 11.30340883, 11.29914543, 11.33722007, 11.30340883,
       11.30271204, 11.25861835, 11.2452798 , 11.30067109, 11.30340883,
       11.27079024, 11.81878746, 11.32050876, 11.33424844, 11.44392992,
       11.84737106, 12.83615939, 11.8233087 , 11.80960827, 11.82045576,
       12.73027602, 12.14584608, 12.61639169, 11.980811  , 12.87548371,
       12.02798651, 11.55464406, 11.94152219, 11.86773393, 11.86727177,
       11.86085954, 11.75427752, 11.46330451, 11.66497643, 11.71996205,
       12.04964091, 11.66816305, 11.80172551, 11.74868283, 11.4665305 ,
       11.9227889 , 12.01189432, 12.20352399, 11.49983663, 11.39058514,
       11.31789628, 12.17365428, 11.5230575 , 11.58949655, 11.42340801,
       11.52501013, 11.40297917, 11.34836663, 11.29727766, 11.24769313,
       11.31069625, 11.31069625, 11.33722007, 11.35115195, 11.30067109,
       11.33722007, 11.26250499, 11.4805244 , 11.42501147, 11.4638875 ,
       12.59981457, 12.23036191, 11.72961778, 12.48459886, 13.11506382,
       13.26033468, 13.14844376, 13.07228104, 12.91571076, 12.53855163,
       12.70714069, 12.74962342, 11.94188747, 11.65337769, 11.86467771,
       11.88130716, 11.84453915, 11.67040016, 11.84752395, 12.08451089,
       11.53606021, 11.60978751, 11.49597337, 11.7049421 , 11.66736056,
       11.43384652, 11.47638131, 11.4665305 , 11.75216004, 11.5476724 ,
       11.78553088, 11.31380786, 11.33553121, 11.49856494, 11.31287165,
       11.44638648, 11.30340883, 11.29727766, 11.31789628, 11.24171319,
       11.31999489, 11.3040902 , 11.31531614, 11.30579128, 11.24769313,
       11.2452798 , 11.30104347, 11.31531614, 11.2452798 , 11.29560909,
       11.24769313, 12.06427512, 11.55452198, 11.77255181, 11.36674688,
       12.50955169, 12.44281321, 12.84940307, 12.83743403, 12.88496745,
       13.02970385, 13.01389695, 12.89008369, 12.48944727, 11.69094052,
       11.95020391, 11.65869737, 11.69938631, 11.65588608, 11.66728936,
       11.67301367, 11.68707332, 11.75386902, 12.06891957, 12.3333017 ,
       12.08042609, 12.17506465, 12.69418445, 12.61410214, 11.57522118,
       12.1107776 , 12.46010026, 12.47080681, 11.93432555, 11.5000525 ,
       11.6321738 , 11.61219213, 11.51131763, 11.53708408, 11.5548872 ,
       11.39788421, 11.33596717, 11.33182065, 11.33375475, 11.31146585,
       11.29543044, 11.30329264, 11.31830603, 11.30271204, 11.31830603,
       11.31789628, 11.30340883, 11.24769313, 11.26218496, 11.44664875,
       11.77727148, 12.13276886, 12.53237537, 11.95056729, 12.90020467,
       12.8889227 , 13.00327042, 12.15028117, 12.11491374, 12.3733458 ,
       12.93892171, 12.08694753, 11.79734624, 11.4665305 , 11.67281877,
       11.47743131, 11.81713317, 11.75013835, 11.66277356, 11.67747181,
       11.66764162, 11.8082612 , 11.46541931, 11.47735852, 11.42501147,
       11.52242055, 11.69705925, 11.72442219, 11.76755751, 11.49787315,
       11.88500336, 11.31993722, 11.28801542, 11.31628776, 11.29914543,
       11.4904403 , 11.31789628, 11.39385479, 11.35863953, 11.30271204,
       11.35913616, 11.2512574 , 11.30271204, 11.30067109, 11.30271204,
       11.34135668, 11.32063402, 11.35410855, 11.4154106 , 11.38988394,
       12.44489227, 11.73577634, 11.43506162, 11.95320574, 12.27755758,
       12.43107477, 12.48637876, 12.58895344, 12.57280308, 12.74763464,
       12.99609198, 12.98463424, 13.03964945, 12.90187582, 12.30167597,
       12.37480937, 11.87833177, 12.39809915, 11.86287274, 11.67213478,
       11.68580574, 11.65869737, 11.68270211, 11.66600429, 12.22301709,
       11.59500103, 11.8267366 , 11.89588485, 12.20130049, 12.34129852,
       11.75936989, 12.54524677, 12.4028056 , 11.94630535, 11.97574569,
       11.65399077, 11.63171867, 11.60316079, 11.33706558, 11.44704759,
       11.34377954, 11.28989243, 11.39116575, 11.41987203, 11.4536023 ,
       11.30271204, 11.26220379, 11.31531614, 11.29969731, 11.33395383,
       11.26784785, 11.42863924, 12.08362484, 11.73104912, 11.43495895,
       11.98759167, 11.43124229, 12.13005259, 11.51696913, 12.63102975,
       12.93533856, 12.96085638, 12.79697159, 12.51344079, 13.19516614,
       12.53287325, 11.65588608, 11.86794154, 11.69155069, 12.62806998,
       11.83656547, 12.20952894, 12.49411353, 12.35946092, 12.2212242 ,
       12.15301932, 12.20394031, 12.37067188, 12.50723219, 12.46151444,
       11.60548296, 11.57651804, 11.89758564, 11.95356856, 11.92791531,
       12.01472478, 11.58831058, 11.66483986, 11.58177389, 11.7024221 ,
       11.30445391, 11.53372198, 11.47593364, 11.36487331, 11.37525362,
       11.34830486, 11.44042139, 11.32267423, 11.30716615, 11.30271204,
       11.28816748, 11.26784785, 11.30271204, 11.31789628, 11.24850638,
       11.3508389 , 11.27941014, 11.43433185, 11.75426443, 11.98687795,
       12.24709668, 12.79078292, 12.70504448, 12.82935198, 13.0442477 ,
       12.51625535, 11.84732655, 12.15938157, 11.80076127, 11.78425119,
       11.75375494, 11.88615915, 12.55842442, 11.70241863, 12.18238754,
       12.08205247, 11.67261041, 12.21572574, 11.61707608, 12.42304774,
       11.70086024, 11.74155047, 12.10518122, 12.39182823, 11.73975094,
       12.4517095 , 12.45582108, 12.56940604, 11.72476765, 11.89748075,
       11.72140637, 11.98892661, 11.89044977, 11.84198632, 11.48938414,
       11.48913372, 11.33606699, 11.37739492, 11.36004108, 11.35668725,
       11.31473942, 11.31531614, 11.32925242, 11.29914543, 11.29727766,
       11.29914543, 11.2512574 , 11.26355499, 11.41524805, 12.10188004,
       12.49597612, 11.67367897, 11.93462376, 12.6540367 , 12.07853934,
       12.99420178, 12.4786148 , 12.4919999 , 11.77534011, 11.71534801,
       11.98353812, 11.90021741, 12.14349162, 11.93632159, 12.19381376,
       11.90040767, 12.19364997, 12.22707168, 12.39091853, 11.64188766,
       11.77463627, 11.75949295, 12.47150548, 12.46578998, 11.89968896,
       11.61558535, 11.93686009, 11.93989359, 12.48959102, 12.46984072,
       11.35349211, 11.7080829 , 11.64568805, 11.21997896, 11.21997896,
       11.64198208, 11.42303482, 11.49970131, 11.3989559 , 11.42462549])

In [14]:
accuracy=regressor.score(test,y1_test)
accuracy

1.0

In [15]:
test['QV2M']=y1_test #adding column to test dataset
test

,ID,YEAR,T2M_RANGE,T2M_MAX,T2M_MIN,RH2M,PS,WS10M,QV2M
0,1440,2009.0,-309.569706,32.919144,17.735611,74.415249,82.443918,6.513046,11.675487
1,1441,2009.0,-310.763533,32.340370,17.955298,75.232482,82.320169,5.163099,11.734918
2,1442,2009.0,-313.096292,29.670217,17.788919,80.950265,82.456590,3.974139,12.089051
3,1443,2009.0,-312.110915,29.586632,16.777071,82.254238,82.460926,5.504794,11.637503
4,1444,2009.0,-312.445008,30.088295,17.233512,81.311915,82.326908,5.634695,11.772414
...,...,...,...,...,...,...,...,...,...
695,2135,2022.0,-310.857597,28.357413,15.023100,86.599317,82.511107,2.637025,11.641982
696,2136,2022.0,-312.033878,26.943856,14.236847,85.965911,82.748450,3.636588,11.423035
697,2137,2022.0,-312.869384,26.542410,14.972372,88.082615,82.626626,3.840101,11.499701
698,2138,2022.0,-308.938303,27.599339,12.882619,84.585012,82.632252,3.306362,11.398956
699,2139,2022.0,-310.589598,28.341680,14.604535,85.173914,82.874200,3.522586,11.424625

In [16]:
X2_train=train.drop(['T2M','VACATION_RATE'],axis=1)
X2_train

,ID,YEAR,T2M_RANGE,T2M_MAX,T2M_MIN,RH2M,PS,WS10M,QV2M
0,0,1982.0,-241.552430,29.798545,13.691128,71.652934,89.725069,3.658959,8.474319
1,1,1982.0,-241.819997,30.902708,15.298046,69.754933,89.865668,3.529113,8.988374
2,2,1982.0,-241.883202,30.296561,14.660419,66.661416,89.846273,4.217007,8.474923
3,3,1982.0,-242.007629,30.803224,15.246491,67.621173,90.029795,4.484080,9.005508
4,4,1982.0,-240.659332,32.500906,15.303059,62.097329,89.825707,3.057211,8.307515
...,...,...,...,...,...,...,...,...,...
1434,1434,2009.0,-246.654914,30.644813,20.268662,78.611410,89.333566,6.433604,13.258977
1435,1435,2009.0,-247.651283,29.857874,20.425241,78.136636,89.324790,7.638996,12.717079
1436,1436,2009.0,-247.594571,30.330303,21.123513,77.497787,89.334675,8.939772,13.058350
1437,1437,2009.0,-247.083708,30.646652,20.883603,75.857655,89.465743,7.663743,12.805387
1438,1438,2009.0,-246.099233,32.191877,21.121979,75.757341,89.528083,6.426315,13.028215

In [17]:
y2_train=train["T2M"]
y2_train

0       21.723403
1       22.911522
2       22.994887
3       23.594655
4       24.536776
          ...
1434    26.685352
1435    25.991700
1436    26.619025
1437    26.923294
1438    27.318661
Name: T2M, Length: 1439, dtype: float64

In [18]:
#to predict T2M using train
regressor.fit(X2_train,y2_train)
pred2=regressor.predict(X2_train) 
pred2

array([21.87072375, 23.19371882, 22.91922125, ..., 26.65918652,
       26.88885606, 27.41999859])

In [19]:
y2_train.round(0)

0       22.0
1       23.0
2       23.0
3       24.0
4       25.0
        ...
1434    27.0
1435    26.0
1436    27.0
1437    27.0
1438    27.0
Name: T2M, Length: 1439, dtype: float64

In [20]:
accuracy=regressor.score(X2_train,y2_train)
accuracy

0.9990266333284678

In [21]:
#T2M prediction on test.csv 
y2_test= regressor.predict(test)
test['T2M']=y2_test #adding T2M column to test
test

,ID,YEAR,T2M_RANGE,T2M_MAX,T2M_MIN,RH2M,PS,WS10M,QV2M,T2M
0,1440,2009.0,-309.569706,32.919144,17.735611,74.415249,82.443918,6.513046,11.675487,26.167339
1,1441,2009.0,-310.763533,32.340370,17.955298,75.232482,82.320169,5.163099,11.734918,25.921587
2,1442,2009.0,-313.096292,29.670217,17.788919,80.950265,82.456590,3.974139,12.089051,24.558697
3,1443,2009.0,-312.110915,29.586632,16.777071,82.254238,82.460926,5.504794,11.637503,23.945287
4,1444,2009.0,-312.445008,30.088295,17.233512,81.311915,82.326908,5.634695,11.772414,24.209900
...,...,...,...,...,...,...,...,...,...,...
695,2135,2022.0,-310.857597,28.357413,15.023100,86.599317,82.511107,2.637025,11.641982,22.139281
696,2136,2022.0,-312.033878,26.943856,14.236847,85.965911,82.748450,3.636588,11.423035,21.544232
697,2137,2022.0,-312.869384,26.542410,14.972372,88.082615,82.626626,3.840101,11.499701,21.729098
698,2138,2022.0,-308.938303,27.599339,12.882619,84.585012,82.632252,3.306362,11.398956,20.581401
699,2139,2022.0,-310.589598,28.341680,14.604535,85.173914,82.874200,3.522586,11.424625,21.982024

In [22]:
X3_train=train.drop('VACATION_RATE',axis=1)
X3_train

,ID,YEAR,T2M_RANGE,T2M_MAX,T2M_MIN,RH2M,PS,WS10M,QV2M,T2M
0,0,1982.0,-241.552430,29.798545,13.691128,71.652934,89.725069,3.658959,8.474319,21.723403
1,1,1982.0,-241.819997,30.902708,15.298046,69.754933,89.865668,3.529113,8.988374,22.911522
2,2,1982.0,-241.883202,30.296561,14.660419,66.661416,89.846273,4.217007,8.474923,22.994887
3,3,1982.0,-242.007629,30.803224,15.246491,67.621173,90.029795,4.484080,9.005508,23.594655
4,4,1982.0,-240.659332,32.500906,15.303059,62.097329,89.825707,3.057211,8.307515,24.536776
...,...,...,...,...,...,...,...,...,...,...
1434,1434,2009.0,-246.654914,30.644813,20.268662,78.611410,89.333566,6.433604,13.258977,26.685352
1435,1435,2009.0,-247.651283,29.857874,20.425241,78.136636,89.324790,7.638996,12.717079,25.991700
1436,1436,2009.0,-247.594571,30.330303,21.123513,77.497787,89.334675,8.939772,13.058350,26.619025
1437,1437,2009.0,-247.083708,30.646652,20.883603,75.857655,89.465743,7.663743,12.805387,26.923294
1438,1438,2009.0,-246.099233,32.191877,21.121979,75.757341,89.528083,6.426315,13.028215,27.318661

In [23]:
y3_train=train["VACATION_RATE"]
y3_train

0       64.184741
1       42.649137
2       52.819141
3       39.445489
4       46.444289
          ...
1434     6.391643
1435     1.920453
1436     7.144639
1437     4.886901
1438    11.217462
Name: VACATION_RATE, Length: 1439, dtype: float64

In [24]:
#to predict using train
regressor.fit(X3_train,y3_train)
pred3=regressor.predict(X3_train) # VACATION RATE
pred3

array([63.44404548, 41.92572915, 52.15717799, ...,  7.57533234,
        5.35129377, 10.83215654])

In [25]:
y3_train[:10]

0    64.184741
1    42.649137
2    52.819141
3    39.445489
4    46.444289
5    29.495610
6    56.122047
7    71.968916
8    42.072725
9    19.738869
Name: VACATION_RATE, dtype: float64

In [26]:
y3_test=regressor.predict(test).astype(int)
test['VACATION_RATE']=y3_test
test

,ID,YEAR,T2M_RANGE,T2M_MAX,T2M_MIN,RH2M,PS,WS10M,QV2M,T2M,VACATION_RATE
0,1440,2009.0,-309.569706,32.919144,17.735611,74.415249,82.443918,6.513046,11.675487,26.167339,2
1,1441,2009.0,-310.763533,32.340370,17.955298,75.232482,82.320169,5.163099,11.734918,25.921587,1
2,1442,2009.0,-313.096292,29.670217,17.788919,80.950265,82.456590,3.974139,12.089051,24.558697,1
3,1443,2009.0,-312.110915,29.586632,16.777071,82.254238,82.460926,5.504794,11.637503,23.945287,6
4,1444,2009.0,-312.445008,30.088295,17.233512,81.311915,82.326908,5.634695,11.772414,24.209900,5
...,...,...,...,...,...,...,...,...,...,...,...
695,2135,2022.0,-310.857597,28.357413,15.023100,86.599317,82.511107,2.637025,11.641982,22.139281,19
696,2136,2022.0,-312.033878,26.943856,14.236847,85.965911,82.748450,3.636588,11.423035,21.544232,23
697,2137,2022.0,-312.869384,26.542410,14.972372,88.082615,82.626626,3.840101,11.499701,21.729098,22
698,2138,2022.0,-308.938303,27.599339,12.882619,84.585012,82.632252,3.306362,11.398956,20.581401,47
699,2139,2022.0,-310.589598,28.341680,14.604535,85.173914,82.874200,3.522586,11.424625,21.982024,23

In [27]:
test1=test[['ID','VACATION_RATE']]

In [28]:
test1.to_csv('submission.csv', sep=',', index=False)
test1

       ID  VACATION_RATE
0    1440              2
1    1441              1
2    1442              1
3    1443              6
4    1444              5
..    ...            ...
695  2135             19
696  2136             23
697  2137             22
698  2138             47
699  2139             23

[700 rows x 2 columns]